### ISSUE TITLE
Instances, Accessors and Basic Combinators

### ISSUE THREAD

**Issue by emilypi** [mitchellwrosen/strict-tuple#1]
Hi @mitchellwrosen - 

I'm raising this issue to see if you'd be amenable to a PR with basic accessors, combinators, and instances for `T1`, `T2`, etc. 

For example `TN` for `N > 1` has a clear `Foldable`, `Traversable`, and `Bifunctor` instance, and the basic accessors and combinators one would expect would be something like `fst` and `snd` for `T2` (n-projections etc.), and curry/uncurry + swap operators. I have vendored most of this in elsewhere, but I would love to contribute this to your library if you're willing to take it. 

Thanks!

**Comment by mitchellwrosen** [comment]
Of course! :)

**Comment by mitchellwrosen** [comment]
#2
