### ISSUE TITLE
Support bifunctors 6

### ISSUE THREAD

**Issue by Topsii** [mitchellwrosen/strict-tuple#7]
In the coming bifunctors-6 release, [the reexport of `Data.Bifunctor` from `Data.Biapplicative` has been removed.](https://github.com/ekmett/bifunctors/blob/4f1535a2c94788c9e6d9accfca8c58ef497628c5/src/Data/Biapplicative.hs)
I suggest to fix the imports:
```diff
- import Data.Biapplicative
+ import Data.Bifunctor
```

**Comment by mitchellwrosen** [comment]
Thanks!
